# Generated by Django 3.2.3 on 2021-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210528_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_id',
        ),
    ]
