# Generated by Django 3.2.3 on 2021-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_user_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstohomeworks',
            old_name='value',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='studentstohomeworks',
            name='status',
            field=models.CharField(choices=[('C', 'complitedt'), ('N', 'not completed')], default='N', max_length=1),
        ),
    ]
