# Generated by Django 3.2.3 on 2021-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20210602_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstohomeworks',
            name='status',
            field=models.CharField(choices=[('C', 'complited'), ('N', 'not completed')], default='N', max_length=1),
        ),
    ]
