# Generated by Django 3.2.3 on 2021-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_studentstohomeworks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstohomeworks',
            name='status',
            field=models.CharField(choices=[('C', 'completed'), ('N', 'not completed')], default='N', max_length=1),
        ),
    ]
