# Generated by Django 3.2.3 on 2021-06-02 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_auto_20210602_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersToHomeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('C', 'completed'), ('N', 'not completed')], default='N', max_length=1)),
                ('student_comment', models.TextField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('homework_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lesson.homework')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentsToHomeworks',
        ),
    ]
