# Generated by Django 3.2.3 on 2021-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_auto_20210602_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstohomeworks',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'completed'), ('N', 'not completed')], max_length=1, null=True),
        ),
    ]
